apiVersion: mock.digi.dev/v1
kind: Phone
metadata:
  name: {{ .Values.name }}
spec:
  meta:
    report_interval: 5
  ingress:
    footprint:
      sources: [ kind:any@energy ]
      flow: "sort -r event_ts | head "
      flow_agg: "select sum(watt) as watt"
      eoio: false
  egress:
    footprint:
      flow: "avg(watt) by every(1h) | sum(avg * 3600)"
    spl:
      flow: "spl | cut spl,event_ts"
