apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cargos.mock.digi.dev
spec:
  group: mock.digi.dev
  names:
    kind: Cargo
    listKind: CargoList
    plural: cargos
    singular: cargo
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties: {}
            type: object
        type: object
    served: true
    storage: true
