apiVersion: mock.digi.dev/v1
kind: Airport
metadata:
  name: {{ .Values.name }}
spec:
  egress:
    delay:
      flow: |-
        switch park (case true => head |
        yield {name:name, arrive_ts:event_ts} case false => head |
        yield {name:name, depart_ts:event_ts}) |
        join on name=name depart_ts:=depart_ts |
        yield {name:name,delay:duration(depart_ts - arrive_ts)} | delay > 0
      eoio: false
