#!/usr/bin/env python3
import os
import sys

import sqlalchemy
import psycopg2

USER = os.environ.get("PGUSER", "postgres")
PASSWD = os.environ.get("PGPASSWORD", "digi")
DB = os.environ.get("DB", "digi")


def db_conn(conn_str=f"postgresql://{USER}:{PASSWD}@localhost/{DB}",
            use_sqlalchemy=False):
    if use_sqlalchemy:
        db = sqlalchemy.create_engine(conn_str)
        return db.connect()
    else:
        return psycopg2.connect(conn_str)

conn = db_conn()

# insert CSV file into given table
def insert(table_name):
    cur = conn.cursor()
    copy_sql = """
            COPY {table} FROM stdin WITH CSV HEADER
            DELIMITER as ','
            """.format(table=table_name)
    cur.copy_expert(sql=copy_sql, file=sys.stdin)
    conn.commit()
    cur.close()

insert(os.environ["NAME"])
conn.close()
