apiVersion: mock.digi.dev/v1
kind: Campus
metadata:
  name: {{ .Values.name }}
spec:
  ingress:
    energy:
      sources: [ kind:building@energy ]
      flow: ""
      patch_source: true
  egress:
    energy:
      flow: "watt | cut watt,event_ts"
