apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rooms.mock.digi.dev
spec:
  group: mock.digi.dev
  names:
    kind: Room
    listKind: RoomList
    plural: rooms
    singular: room
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              meta:
                properties:
                  gen_interval:
                    type: number
                  managed:
                    type: boolean
                  seed:
                    type: number
                type: object
              mount:
                properties:
                  mock.digi.dev/v1/appliances:
                    additionalProperties:
                      properties:
                        generation:
                          type: number
                        mode:
                          type: string
                        spec: &id001
                          properties:
                            control:
                              properties:
                                power:
                                  properties:
                                    intent:
                                      type: string
                                    status:
                                      type: string
                                  type: object
                              type: object
                            egress:
                              properties:
                                energy:
                                  properties:
                                    eoio:
                                      type: boolean
                                    flow:
                                      type: string
                                  type: object
                              type: object
                            meta:
                              properties:
                                unit:
                                  type: string
                                wattage:
                                  type: number
                              type: object
                            obs:
                              properties:
                                watt:
                                  type: number
                              type: object
                          type: object
                        status:
                          type: string
                      type: object
                    type: object
                  mock.digi.dev/v1/densities:
                    additionalProperties:
                      properties:
                        generation:
                          type: number
                        mode:
                          type: string
                        spec:
                          properties:
                            egress:
                              properties:
                                avg_count:
                                  properties:
                                    eoio:
                                      type: boolean
                                    flow:
                                      type: string
                                  type: object
                                count:
                                  properties:
                                    eoio:
                                      type: boolean
                                    flow:
                                      type: string
                                  type: object
                              type: object
                            meta:
                              properties:
                                report_interval:
                                  type: number
                              type: object
                            obs:
                              properties:
                                count:
                                  type: number
                              type: object
                          type: object
                        status:
                          type: string
                      type: object
                    type: object
                  mock.digi.dev/v1/lamps:
                    additionalProperties:
                      properties:
                        generation:
                          type: number
                        mode:
                          type: string
                        spec: &id002
                          properties:
                            control:
                              properties:
                                brightness:
                                  properties:
                                    intent:
                                      type: number
                                    status:
                                      type: number
                                  type: object
                                power:
                                  properties:
                                    intent:
                                      type: string
                                    status:
                                      type: string
                                  type: object
                              type: object
                            meta:
                              properties:
                                gen_interval:
                                  type: number
                                managed:
                                  type: boolean
                                wattage:
                                  type: number
                              type: object
                          type: object
                        status:
                          type: string
                      type: object
                    type: object
                  mock.digi.dev/v1/occupancies:
                    additionalProperties:
                      properties:
                        generation:
                          type: number
                        mode:
                          type: string
                        spec:
                          properties:
                            meta:
                              properties:
                                gen_interval:
                                  type: number
                                managed:
                                  type: boolean
                                seed:
                                  type: number
                              type: object
                            obs:
                              properties:
                                battery_level:
                                  type: number
                                dbm:
                                  type: string
                                motion_detected:
                                  type: boolean
                                supply_voltage:
                                  type: string
                              type: object
                          type: object
                        status:
                          type: string
                      type: object
                    type: object
                  mock.digi.dev/v1/phones:
                    additionalProperties:
                      properties:
                        generation:
                          type: number
                        mode:
                          type: string
                        spec:
                          properties:
                            egress:
                              properties:
                                footprint:
                                  properties:
                                    driver_managed:
                                      type: boolean
                                    eoio:
                                      type: boolean
                                    flow:
                                      type: string
                                    pause:
                                      type: boolean
                                  type: object
                                spl:
                                  properties:
                                    driver_managed:
                                      type: boolean
                                    eoio:
                                      type: boolean
                                    flow:
                                      type: string
                                    pause:
                                      type: boolean
                                  type: object
                              type: object
                            ingress:
                              properties:
                                footprint:
                                  properties:
                                    eoio:
                                      type: boolean
                                    flow:
                                      type: string
                                    flow_agg:
                                      type: string
                                    patch_source:
                                      type: boolean
                                    pause:
                                      type: boolean
                                    source:
                                      items:
                                        properties:
                                          egress:
                                            type: string
                                          group:
                                            type: string
                                          kind:
                                            type: string
                                          name:
                                            type: string
                                          namespace:
                                            type: string
                                          version:
                                            type: string
                                        type: object
                                      type: array
                                    sources:
                                      items:
                                        type: string
                                      type: array
                                  type: object
                              type: object
                            meta:
                              properties:
                                report_interval:
                                  type: number
                              type: object
                            mount:
                              properties:
                                mock.digi.dev/v1/appliances:
                                  additionalProperties:
                                    properties:
                                      generation:
                                        type: number
                                      mode:
                                        type: string
                                      spec: *id001
                                      status:
                                        type: string
                                    type: object
                                  type: object
                                mock.digi.dev/v1/lamps:
                                  additionalProperties:
                                    properties:
                                      generation:
                                        type: number
                                      mode:
                                        type: string
                                      spec: *id002
                                      status:
                                        type: string
                                    type: object
                                  type: object
                              type: object
                          type: object
                        status:
                          type: string
                      type: object
                    type: object
                  mock.digi.dev/v1/scenes:
                    additionalProperties:
                      properties:
                        generation:
                          type: number
                        mode:
                          type: string
                        spec:
                          properties:
                            data:
                              properties:
                                input:
                                  properties:
                                    objects:
                                      items:
                                        properties:
                                          class:
                                            type: string
                                          location:
                                            properties:
                                              h:
                                                type: number
                                              w:
                                                type: number
                                              x1:
                                                type: number
                                              x2:
                                                type: number
                                            type: object
                                          name:
                                            type: string
                                        type: object
                                      type: array
                                    url:
                                      type: string
                                  type: object
                                output:
                                  properties:
                                    objects:
                                      items:
                                        properties:
                                          class:
                                            type: string
                                          location:
                                            properties:
                                              h:
                                                type: number
                                              w:
                                                type: number
                                              x1:
                                                type: number
                                              x2:
                                                type: number
                                            type: object
                                          name:
                                            type: string
                                        type: object
                                      type: array
                                  type: object
                              type: object
                            meta:
                              properties:
                                mode:
                                  type: string
                                object_config:
                                  additionalProperties:
                                    properties:
                                      class:
                                        type: string
                                      enter_prob:
                                        type: number
                                      leave_prob:
                                        type: number
                                    type: object
                                  type: object
                                pause:
                                  type: boolean
                                refresh_interval:
                                  type: number
                              type: object
                            obs:
                              properties:
                                reason:
                                  type: string
                              type: object
                          type: object
                        status:
                          type: string
                      type: object
                    type: object
                  mock.digi.dev/v1/underdesks:
                    additionalProperties:
                      properties:
                        generation:
                          type: number
                        mode:
                          type: string
                        spec:
                          properties:
                            egress:
                              properties:
                                detected:
                                  properties:
                                    driver_managed:
                                      type: boolean
                                    eoio:
                                      type: boolean
                                    flow:
                                      type: string
                                    pause:
                                      type: boolean
                                  type: object
                              type: object
                            meta:
                              properties:
                                report_interval:
                                  type: number
                              type: object
                            obs:
                              properties:
                                dbm:
                                  type: string
                                motion_detected:
                                  type: boolean
                                supply_voltage:
                                  type: string
                              type: object
                          type: object
                        status:
                          type: string
                      type: object
                    type: object
                type: object
              obs:
                properties:
                  human_presence:
                    type: boolean
                type: object
            type: object
        type: object
    served: true
    storage: true
