apiVersion: mock.digi.dev/v1
kind: Group
metadata:
  name: {{ .Values.name }}
spec:
  ingress:
    energy:
      sources: [ kind:room@energy ]
      flow: ""
      patch_source: true
    occupancy:
      sources: [ kind:room@occupancy ]
      flow: "TBD"
  egress:
    energy:
      flow: "watt | cut watt,event_ts"
    occupancy:
      flow: "occupancy | cut occupancy,event_ts"
    # Correlation
