apiVersion: mock.digi.dev/v1
kind: Multiscene
metadata:
  name: {{ .Values.name }}
spec:
  meta:
    scene_prefix: s
    num_scene: 3
    refresh_interval: 10 # TBD test with lower value
    pause: false
    object_config:
      alice:
        enter_prob: 0.5
        leave_prob: 0.5
        class: human
      bob:
        enter_prob: 0.2
        leave_prob: 0.5
        class: human
      charlie:
        enter_prob: 0.8
        leave_prob: 0.5
        class: human
      dog:
        enter_prob: 0.2
        leave_prob: 0.1
        class: dog
