apiVersion: mock.digi.dev/v1
kind: Building
metadata:
  name: {{ .Values.name }}
spec:
  ingress:
    energy:
      sources: [ kind:any@energy ]
      flow: ""
      flow_agg: ""
      patch_source: true
    occupancy:
      sources: [ kind:room@occupancy ]
      flow: "sort -r event_ts | head"
      eoio: false
  egress:
    energy:
      flow: "watt | cut watt,event_ts"
    occupancy:
      pause: true
