apiVersion: mock.digi.dev/v1
kind: Floor
metadata:
  name: {{ .Values.name }}
spec:
  ingress:
    energy:
      sources: [ kind:room@energy]
      flow: ""
      patch_source: true
  egress:
    energy:
      flow: "watt | cut watt,event_ts"
